[asciidocExt]
extensions = [
  "asciidoctor-diagram",
  "asciidoctor-foodogsquared-extensions",
]
trace = true
workingFolderCurrent = true

[asciidocExt.attributes]
toc = true
sectanchors = true
"figure-caption!" = true
source-highlighter = "rouge"
allow-uri-read = true
experimental = true
linkcss = true
cache-uri = true
reproducible = true
stem = "latexmath"
env-hugo = true

avatarsdir = "/nix-module-wrapper-manager-fds/icons/avatars"
avatarstype = "svg"

icons = "image"
iconsdir = "/nix-module-wrapper-manager-fds/icons/asciidoctor"
icontype = "svg"
